# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

use_frameworks!


pod 'Alamofire'
pod 'SwiftyJSON'
pod 'BmobSDK'
pod 'SwiftOverlays'

pod 'QRCodeReader.swift'



pod 'PDTSimpleCalendar'
pod 'ChameleonFramework/Swift'
pod 'TextFieldEffects'

pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
pod 'Charts'



target 'WOLFMP' do

end

target 'WOLFMPTests' do

end

