# Uncomment this line to define a global platform for your project

platform :ios, '8.0'

use_frameworks!


pod 'Alamofire'
pod 'SwiftyJSON'
pod 'BmobSDK'
pod 'ToastSwift'
pod 'SwiftOverlays'
pod 'SwiftFilePath'
pod 'SwiftDictModel'
pod 'QRCodeReader.swift'
#pod 'ExSwift'


pod 'PDTSimpleCalendar'
pod 'ChameleonFramework/Swift'
pod 'TextFieldEffects'
pod 'MGSwipeTableCell'
pod 'Spring'
pod 'ios-charts'
pod 'RongCloudKit'


target 'WOLFMP' do

end

target 'WOLFMPTests' do

end

